// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXtMecpO7ia5t9p9ct4onEn7pqEXd-QfA',
    appId: '1:562750650926:web:932a8d27af46e3b34b3dbf',
    messagingSenderId: '562750650926',
    projectId: 'faceapp-de745',
    authDomain: 'faceapp-de745.firebaseapp.com',
    storageBucket: 'faceapp-de745.appspot.com',
    measurementId: 'G-G1K0PQ0JEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx9T_EvUDOXdYrwoXwP0yWQUasItJRUjw',
    appId: '1:562750650926:android:9134d58fad3fab394b3dbf',
    messagingSenderId: '562750650926',
    projectId: 'faceapp-de745',
    storageBucket: 'faceapp-de745.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR_subI8qLoayhbMFJvUMuiwR96Gi4a4U',
    appId: '1:562750650926:ios:460f1f82a9812ea74b3dbf',
    messagingSenderId: '562750650926',
    projectId: 'faceapp-de745',
    storageBucket: 'faceapp-de745.appspot.com',
    iosBundleId: 'com.example.facesecure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBR_subI8qLoayhbMFJvUMuiwR96Gi4a4U',
    appId: '1:562750650926:ios:460f1f82a9812ea74b3dbf',
    messagingSenderId: '562750650926',
    projectId: 'faceapp-de745',
    storageBucket: 'faceapp-de745.appspot.com',
    iosBundleId: 'com.example.facesecure',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXtMecpO7ia5t9p9ct4onEn7pqEXd-QfA',
    appId: '1:562750650926:web:a4035b65aa0d82d84b3dbf',
    messagingSenderId: '562750650926',
    projectId: 'faceapp-de745',
    authDomain: 'faceapp-de745.firebaseapp.com',
    storageBucket: 'faceapp-de745.appspot.com',
    measurementId: 'G-6Y3K57WNJ6',
  );
}
